---
roles:
  - name: arillso.restic
    version: 0.3.0
  - name: weareinteractive.users
    version: 1.17.0
  - name: gantsign.golang
    version: 2.9.6
  - name: geerlingguy.docker
    version: 4.1.1
  - name: geerlingguy.ntp
    version: 2.3.0
  - name: geerlingguy.pip
    version: 2.1.0
  - name: geerlingguy.security
    version: 2.1.0
  - name: artis3n.tailscale
    version: v1.16.0

  - name: warhorse.cobaltstrike_docker
  - name: warhorse.neo4j_docker
  - name: warhorse.traefik_docker
  - name: warhorse.nighthawk_docker
  - name: warhorse.gophish_docker
  - name: warhorse.evilginx2_docker
  - name: warhorse.nginx_docker
  - name: warhorse.parrotos_docker

  - name: t94j0.mythic

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
  - name: amazon.aws