- name: "{{ name }} Digital Ocean Terraform Cloud"
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    workspace: "{{ warhorse.terraform.cloud_workspace }}"
    force_init: true
    variables:
      do_token: "{{ warhorse.terraform.digitalocean_token }}"
  when: warhorse | regex_search("(?i).+('provider':\s'digitalocean')", multiline=True, ignorecase=True)

- name: "{{ name }} Linode Terraform Cloud"
  community.general.terraform:
    project_path: '{{ terraform_project_path }}'
    state: "{{ state }}"
    workspace: "{{ warhorse.terraform.cloud_workspace }}"
    force_init: true
    variables:
      li_token: "{{ warhorse.terraform.linode_token }}"
  when: warhorse | regex_search("(?i).+("provider":\s"linode")", multiline=True, ignorecase=True)