#!/bin/bash

echo 'Drives:'
echo

longest=0
while read -r name _; do
	len="${#name}"
	if ((len > longest)); then
		longest=$len
	fi
done < <(df -h --output=target | grep -v 'tmpfs\|mergerfs\|/boot\|overlay\|shm' | tail -n +2 | sort)

while read -r mount use fs _; do
	printf "     %s%*s" "$mount" "$((longest - ${#mount} - 5))" ""

	perc=$(sed 's/%//' <<< "$use")
	if ((perc > 90)); then
		echo -ne "\e[1;31m"
	elif ((perc > 70)); then
		echo -ne "\e[1;33m"
	else
		echo -ne "\e[1;32m"
	fi

	printf "%d%%%b" "$perc" "\e[0m"

	if which snapraid >/dev/null 2>&1; then
		while read -r temp _ err fp _ _ dev di _; do
			if [[ "$fp" = SSD ]]; then
				echo -ne "\t SSD"
			else
				echo -ne "\t $temp°C"

				if ((err > 0)); then
					echo -ne "\t\e[1;31m$err\e[0m"
				fi

				echo -ne "\t($fp failure rate)"
			fi
		done < <(snapraid smart | grep "${fs::-1}")
	fi

	echo
done < <(df -h --output=target,pcent,source,fstype | grep -v 'tmpfs\|mergerfs\|/boot\|overlay\|shm' | tail -n +2 | sort)

echo